### ISSUE TITLE
[Edge] Not able to register plugins

### ISSUE THREAD

**Issue by mwohlan** [unjs/nitro#765]
### Environment

See Stackblitz reproduction

### Reproduction

https://stackblitz.com/edit/github-sn8zkc?file=package.json

### Describe the bug

Getting the following error when trying to register a plugin:

[worker reload] Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/projects/github-sn8zkc/plugins/test' imported from /home/projects/github-sn8zkc/.nitro/dev/index.mjs

**Comment by manniL** [comment]
Was introduced by https://github.com/unjs/nitro/commit/971512044532f1dbec0aa0f21459f55cf62ac349

**Comment by danielroe** [comment]
I think we should likely add back the `isWindows` check. Does that resolve the issue @manniL?

**Comment by pi0** [comment]
not sure if reproducable anymore but please ping to reopen 🙏🏼
